name: golang-pipeline
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        container: golang:1.23
        steps:
            - uses: actions/checkout@v4

            - name: Set up SQLite environment
              run: |
                mkdir -p /app/storage
                touch /app/storage/scheduler.db

            - name: Build and Run Server
              run: |
                go build -o app ./cmd/scheduler/main.go
                ./app &
              continue-on-error: true

            - name: Wait for the server to start
              run: sleep 10

            - name: Run Unit Tests
              run: GOOS=linux GOARCH=amd64 go test ./...

            - name: Vet
              run: |
                go vet ./...