name: golang-pipeline
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Go
          uses: actions/setup-go@v4
          with:
            go-version: 1.23

        - name: Load environment variables
          run: |
              cat .env | grep -v '^#' >> $GITHUB_ENV

        - name: Build the application
          run: |
            go build -o app ./cmd/scheduler/main.go

        - name: Start server in background
          run: |
            ./app & 
            sleep 5  # Даём время серверу на запуск

        - name: Run Unit Tests
          run: |
            GOOS=linux GOARCH=amd64 go test ./...

        - name: Print server logs (for debugging)
          run: |
            cat server.log || true